### ISSUE TITLE
How to re retrieve notifications?

### ISSUE THREAD

**Issue by syunusic** [carbonblack/cbc-syslog#42]
Is it possible to re retrieve notifications? Meaning, I get 2500 messages and for some reason I delete the resultant syslog file and I want to get them again.. how can I do that?
For now, I'm only to get new notifications/events, but not ask for them again.

**Comment by avanbrunt-cb** [comment]
This is not possible because the API acts like a queue so once retrieved they are gone. You can always go through the Alerts API but that doesn't act like a queue
