### ISSUE TITLE
Feature request: Logging to file instead

### ISSUE THREAD

**Issue by vnagendra** [carbonblack/cbc-syslog#5]
Would be nice to be able to specify a Rotating Log file instead of a Syslog Destination in the configuration file. 

Something like this perhaps?http://www.blog.pythonlibrary.org/2014/02/11/python-how-to-create-rotating-logs/

This would allow for a local log file output (instead of a syslog destination), which will enable logstash (or something similar) to pick-up the file in JSON format and deliver to various destinations. 

In our case that's Rabbit/ElasticSearch

**Comment by askthedragon** [comment]
there is a -l flag you can use to log to a file.  Granted it isn't rotating yet.

**Comment by avanbrunt-cb** [comment]
We will be supporting file output as an option in CBC Syslog 2.0 though don't currently plan for rotating logs as each poll cycle will be a new file
