### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by cru-Luis-Rodriguez** [carbonblack/cbc-syslog#53]
Hello, 

I'm trying to understand the CMD line. Should there be an executable in the path? 

https://github.com/carbonblack/cbc-syslog/blob/97e4014617d279a836e5a6ed10dda1020686fb08/docker/Dockerfile#L40

Running the build container as described `sudo docker container run -it <containerId> /bin/bash
` and checking the directory executed on the `CMD` I only find the `store` directory that is created on the Dockerfile. https://github.com/carbonblack/cbc-syslog/blob/97e4014617d279a836e5a6ed10dda1020686fb08/docker/Dockerfile#L33

Should the command be this instead: `CMD ["cbc-syslog", "--config-file", "/etc/cb/integrations/cbc-syslog/cbc-syslog.conf", "--log-file", "/dev/stdout"]
`? I ask because on line https://github.com/carbonblack/cbc-syslog/blob/97e4014617d279a836e5a6ed10dda1020686fb08/docker/Dockerfile#L37 it copies the files from the build image that includes the cbc-syslogs executable into /usr/bin. I'm trying to get this to work on docker, but I get the ` No such file or directory` message. 

Regards,

**Comment by avanbrunt-cb** [comment]
Docker support being rebuilt with CBC Syslog 2.0
