### ISSUE TITLE
Error building docker container

### ISSUE THREAD

**Issue by elmernissi** [carbonblack/cbc-syslog#59]
#10 103.5 Complete!
#10 104.4 Collecting pip
#10 104.8   Downloading https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz (1.5MB)
#10 106.1 Installing collected packages: pip
#10 106.1   Found existing installation: pip 8.1.2
#10 106.1     Uninstalling pip-8.1.2:
#10 106.1       Successfully uninstalled pip-8.1.2
#10 106.1   Running setup.py install for pip: started
#10 107.5     Running setup.py install for pip: finished with status 'done'
#10 107.6 Successfully installed pip-21.0.1
#10 107.8 Traceback (most recent call last):
#10 107.8   File "/usr/bin/pip", line 9, in <module>
#10 107.8     load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
#10 107.8   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
#10 107.8     return get_distribution(dist).load_entry_point(group, name)
#10 107.8   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
#10 107.8     return ep.load()
#10 107.8   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
#10 107.8     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
#10 107.8   File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
#10 107.8     sys.stderr.write(f"ERROR: {exc}")
#10 107.8                                    ^
#10 107.8 SyntaxError: invalid syntax
------
executor failed running [/bin/sh -c yum update -y   && yum install -y gcc python-devel   && yum install -y epel-release   && yum install -y python-pip rpm-build   && pip install --upgrade pip   && pip install pyinstaller==2.7   && mkdir -p     /root/build-root     /root/cbc-syslog     /root/rpmbuild/SOURCES]: exit code: 1

**Comment by avanbrunt-cb** [comment]
Docker support being rebuilt in CBC Syslog 2.0
