### ISSUE TITLE
JSON is the way to go, but suggest change in default CEF syslog format in the example TOML file. 

### ISSUE THREAD

**Issue by SimSama** [carbonblack/cbc-syslog#88]
### Is your feature request related to a problem? Please describe.

Current example script for CEF Alerts are this:
EXAMPLE_ALERT_CEF_TEMPLATE = """
[alerts_template]
template = \"{{datetime_utc}} localhost CEF:1|{{vendor}}|{{product}}|{{product_version}}|{{reason_code}}|{{reason}}|{{severity}}|{{extension}}\"

### Describe the solution you'd like

Would recommend this to make it explicit that this is an alert log to distinguish from the audit logs.

EXAMPLE_ALERT_CEF_TEMPLATE = """
[alerts_template]
template = \"{{datetime_utc}} localhost CEF:1|{{vendor}}|{{product}}|{{product_version}}|**Alert**|{{reason_code}}|{{reason}}|{{severity}}|{{extension}}\"

e.g. <datetime> <host> CEF:1|vendor|product|version|eventType|other fields

### Describe alternatives you've considered

Just a small example recommendation as it appears customers just blindly copy the example toml file, and it make it easy to distinguish log types

**Comment by avanbrunt-cb** [comment]
@SimSama Your recommendation does not follow the standard CEF format header

```
Jan 18 11:07:53 host CEF:Version|Device Vendor|Device Product|Device Version|Device Event Class ID|Name|Severity|[Extension]
```
Reference: https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.3/cef-implementation-standard/Content/CEF/Chapter%201%20What%20is%20CEF.htm

We can't add an additional header element without removing one and for the example we recommended using the `reason_code` as the `Device Event Class ID`. Given this is customizable a customer can configure as they desire should they be concerned with any overlap.
