### ISSUE TITLE
syslog - output file for detail Audit and alert 

### ISSUE THREAD

**Issue by stephanieRopars06480** [carbonblack/cbc-syslog#93]
### Is your feature request related to a problem? Please describe.

Hello
I am configuring a syslog on windows, to have the ouput into a file. Each time I run the following command : cbc_syslog_forwarder --log-file D:\cbc-syslog\logs\cbc-syslog.log -v poll D:\cbc-syslog\my-config.toml, the cbc-syslog.log is incremented with number of alert and audit log . And details is specified in another new files, generated with a random file name  . Each time I launch the command , a new files is created.
Why all informations are not stored in only one file ? Is it possible to configure differently?

### Describe the solution you'd like

I would like to have detail about all alerts/audits in the same file, incremented each time the cbc_syslog_forwarder is launched
Thansk a lot for you help

**Comment by avanbrunt-cb** [comment]
We do not support a single file as each poll cycle is saved to a new file in the output directory. You can create/run additional scripts as desired to manipulate the file as you desire
