### ISSUE TITLE
time zone still in UTC

### ISSUE THREAD

**Issue by stephanieRopars06480** [carbonblack/cbc-syslog#95]
### Describe the bug

Hello
When the poll command is generated, the file created provide time in UTC but we would like local time. Can you please indicate how to do it?
We have tested several config and all provide UTC time
currently our config is :

[alerts_template]
template = "{{datetime_legacy}} localhost CEF:1|{{vendor}}|{{product}}|{{product_version}}|{{reason_code}}|{{reason}}|{{severity}}|{{extension}}"
type_field = "type"
time_format = "%b %d %Y %H:%m:%S "
Thanks for your help

### Reproduction steps

1.
2.
3.
...

### Expected behavior

we would like local time in the log file
Thanks

**Comment by avanbrunt-cb** [comment]
We do not support non UTC time this needs managed on the receiving side
